export const asidebarlocalization = {
  products: "محصولات",
  orders: "سفارشات",
  users: "کاربران",
  logOut: "خروج از حساب کاربری",
  inventory: "موجودی",
};

export const headerLocalization = {
  admin: "مدیر",
  warning: "خطا در دریافت اطلاعات",
  search: "جستجو",
};

export const logInLocalization = {
  email: "نام کاربری",
  password: "رمز عبور",
  submit: "تایید",
  success: "ورود موفقیت‌آمیز بود",
  incorrect: "نام کاربری یا رمز عبور شما نا معتبر است",
  error: "خطا در ورود، لطفاً دوباره تلاش کنید",
  login: "ورود به حساب کاربری",
  notAdmin: "شما دسترسی لازم برای ورود به این پنل را ندارید.",
};

export const inputLocalization = {
  text: "لطفا این قسمت را پر نمایید !",
};

export const productPageLocalization = {
  productList: "لیست محصولات",
  noProduct: "اطلاعاتی یافت نشد",
  image: "تصویر",
  name: "نام",
  status: "وضعیت محصول",
  count: "تعداد موجود",
  price: "قیمت",
  action: "اقدامات",
  toman: "تومان",
  is: "موجود",
  not: "ناموجود",
  addProduct: "افزودت محصول جدید",
  all: "همه محصولات",
  available: "موجودی ها",
  unavailable: "ناموجود ها",
  most: "بیشترین به کم ترین",
  least: "کمترین به بیشترین",
  confirmDelete: "آیا از حذف این محصول اطمینان دارید؟",
  confirmDeleteAlert: "با حذف این محصول، همه اطلاعات مربوط به آن حذف خواهد شد",
  deleteSuccess: "محصول با موفقیت حذف شد",
  deleteError: "خطا در حذف محصول، لطفا دوباره تلاش کنید",
  delete: "حذف",
  cancel: "انصراف",
  ok: "تایید",
};

export const inventoryLocalization = {
  inventory: "لیست موجودی",
};

export const ordersLocalization = {
  user: "نام کاربر",
  totalPrice: "مجموع سفارش",
  deliveryDate: "تاریخ ارسال",
  deliveryStatus: "وضعیت ارسال",
  action: "اقدامات",
  noOrder: "سفارشی یافت نشد",
  orders: "لیست سفارشات",
  sending: "درحال ارسال",
  sended: "ارسال شده",
  all: "همه سفارش‌ها",
  DELIVERED: "ارسال داده شده‌ها",
  NOT_DELIVERED: "ارسال نشده‌ها",
  search: "جستجو بر اساس نام کاربری",
  confirmDelete: "آیا از حذف این سفارش اطمینان دارید؟",
  confirmDeleteAlert: "با حذف این سفارش، همه اطلاعات مربوط به آن حذف خواهد شد",
  deleteSuccess: "سفارش با موفقیت حذف شد",
  deleteError: "خطا در حذف سفارش، لطفا دوباره تلاش کنید",
  delete: "حذف",
  cancel: "انصراف",
  ok: "تایید",
};

export const usersLocalization = {
  userPage: "لیست کاربران",
  firstName: "نام",
  lastName: "نام  خانوادگی",
  userName: "نام کاربری",
  phoneNumber: "شماره تلفن",
  role: "سمت",
  noUser: "کاربری یافت نشد",
  action: "اقدامات",
  user: "کاربر",
  admin: "مدیر",
  confirmDelete: "آیا از حذف این کاربر اطمینان دارید؟",
  confirmDeleteAlert: "با حذف این کاربر، همه اطلاعات مربوط به آن حذف خواهد شد",
  deleteSuccess: "کاربر با موفقیت حذف شد",
  deleteError: "خطا در حذف کاربر، لطفا دوباره تلاش کنید",
  delete: "حذف",
  cancel: "انصراف",
  ok: "تایید",
};

export const tableLocalization = {
  rowsPerPage: "ردیف ها در صفحه",
  page: "صفحه",
  of: "از",
  moreOf: "بیشتر از",
  to: "تا",
  saveChanges: "ذخیره تغییرات",
  saveError: "خطا در ذخیره تغییرات",
  saveSucces: "تغییرات با موفقیت ذخیره شد",
};

export const ModalLocalization = {
  name: "نام محصول",
  quantity: "تعداد موجود",
  price: "قیمت",
  brand: "برند",
  description: "توضیحات",
  images: "تصاویر",
  details: "جزئیات",
  discount: "تخفیف",
  addProduct: "افزودن محصول",
  exit: "انصراف",
  addImage: "افزودن تصویر",
  noImages: "تصویری اضافه نشده است",
  maxImages: "تعداد تصاویر به حد مجاز رسیده است",
  toman: "تومان",
  category: "دسته بندی",
  selectCategory: "انتخاب دسته بندی",
  sanitary: "بهداشتی",
  cosmetics: "لوازم آرایشی",
  subCategory: "زیر دسته بندی",
  selectSubCategory: "انتخاب زیر دسته بندی",
  selectSubCategoryAlert: "لطفا ابتدا دسته بندی مورد نظر را انتخاب کنید",
  Sanitary: "بهداشتی",
  Cosmetics: "آرایشی",
  Hair: "مو",
  Electrical: "الکتریکی",
  Concealer: "کانسیلر",
  PowderCream: "کرم پودر",
  CheekBlush: "رژ گونه",
  Mascara: "ریمل",
  EyeShadow: "سایه چشم",
  Eyeliner: "خط چشم",
  EyePencil: "مداد چشم",
  EyebrowPencil: "مداد ابرو",
  Lipstick: "رژ لب",
  Creams: "کرم‌ها",
  BodyWash: "شستشوی بدن",
  Cleaner: "پاک‌کننده",
  Shampoo: "شامپو",
  HairMask: "ماسک مو",
  HairSerum: "سرم مو",
  HairGel: "ژل مو",
  HairDryer: "سشوار",
  HairStraightener: "اتو مو",
  Sunscreen: "ضد آفتاب",
  trimmer: "تریمر",
  addInput: "افزودن جزئیات",
  colors: "رنگ ها",
  addColor: "افزودن رنگ",
  succes: "محصول با موفقیت اضافه شد",
};
